version: '3.4'
services:
#  Optional
  fileserversng-v62-share:
    image: ${docker.share.image}:${alfresco.share.version}
    environment:
      REPO_HOST: fileserversng-v62-acs
      REPO_PORT: 8080
    ports:
      - "${share.port}:8080"
  fileserversng-v62-acs:
    image: alfresco-content-services-fileserversng-v62:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
    ports:
      - "${acs.port}:8080"
      - "${acs.debug.port}:8888"
      - "445:445"
      - "21:21"
      - "60000-60100:60000-60100"
    volumes:
      - fileserversng-v62-acs-volume:/usr/local/tomcat/alf_data
    depends_on:
      - fileserversng-v62-postgres
  fileserversng-v62-postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "${postgres.port}:5432"
    volumes:
      - fileserversng-v62-db-volume:/var/lib/postgresql/data
  fileserversng-v62-ass:
    image: alfresco/alfresco-search-services:1.2.0
    environment:
      SOLR_ALFRESCO_HOST: fileserversng-v62-acs
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: fileserversng-v62-ass
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
    ports:
      - "8983:8983"
    volumes:
      - fileserversng-v62-ass-volume:/opt/alfresco-search-services/contentstore
      - fileserversng-v62-ass-volume:/opt/alfresco-search-services/data
volumes:
  fileserversng-v62-acs-volume:
    external: true
  fileserversng-v62-db-volume:
    external: true
  fileserversng-v62-ass-volume:
    external: true