version: "3.4"

services:
  fileserversng-v62-share:
    image: alfresco/alfresco-share:6.2.0
    environment:
      REPO_HOST: fileserversng-v62-acs
      REPO_PORT: 8080
    ports:
      - "8180:8080"

  fileserversng-v62-acs:
    image: filesysorg/alfresco-fileserversng-v62:latest
    environment:
      FSNG_SMB_DEBUGFLAGS: "Negotiate,Socket,State,Error,Signing"
    ports:
      - "8080:8080"
      - "445:1445"
      - "21:21"
      - "60000:60100"
    volumes:
      - fileserversng-v62-acs-volume:/usr/local/tomcat/alf_data
      # Licence file should be in a local folder, or only SMB1 will be enabled
      # Request a fileServersNG trial licence by emailing info@filesys.org
      - <MAP-TO-LOCAL-FOLDER>:/usr/local/tomcat/webapps/alfresco/WEB-INF/classes/alfresco/extensions/license
    depends_on:
      - fileserversng-v62-postgres

  fileserversng-v62-postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "5432:5432"
    volumes:
      - fileserversng-v62-db-volume:/var/lib/postgresql/data

  fileserversng-v62-ass:
    image: alfresco/alfresco-search-services:1.2.0
    environment:
      SOLR_ALFRESCO_HOST: fileserversng-v62-acs
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: fileserversng-v62-ass
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
    ports:
      - "8983:8983"
    volumes:
      - fileserversng-v62-ass-volume:/opt/alfresco-search-services/contentstore
      - fileserversng-v62-ass-volume:/opt/alfresco-search-services/data
volumes:
    fileserversng-v62-acs-volume:
        external: true
    fileserversng-v62-db-volume:
        external: true
    fileserversng-v62-ass-volume:
        external: true
