logger.fileserversng.name=org.alfresco.fileServersNG
logger.fileserversng.level=debug

logger.smb-protocol.name=org.alfresco.smb.protocol
logger.smb-protocol.level=debug

logger.ftp-protocol.name=org.alfresco.ftp.protocol
logger.ftp-protocol.level=debug

logger.ftp-server.name=org.alfresco.ftp.server
logger.ftp-server.level=debug

#logger.content-disk-driver2.name=org.filesys.alfresco.repo.ContentDiskDriver2
#logger.content-disk-driver2.level=debug

#logger.temp-network-file.name=org.filesys.alfresco.repo.TempNetworkFile
#logger.temp-network-file.level=debug

#logger.content-comparator.name=org.filesys.alfresco.repo.SMBContentComparator
#logger.content-comparator.level=debug

#logger.nontransactional-rule-driver.name=org.filesys.alfresco.repo.NonTransactionalRuleContentDiskDriver
#logger.nontransactional-rule-driver.level=debug

#logger.legacy-file-state-driver.name=org.filesys.alfresco.repo.LegacyFileStateDriver
#logger.legacy-file-state-driver.level=debug

#logger.buffered-content-disk-driver.name=org.filesys.alfresco.repo.BufferedContentDiskDriver
#logger.buffered-content-disk-driver.level=debug

#logger.smb-authenticator.name=org.filesys.alfresco.auth.smb.AlfrescoSMBAuthenticator
#logger.smb-authenticator.level=debug

#logger.content-disk-driver.name=org.filesys.alfresco.repo.ContentDiskDriver
#logger.content-disk-driver.level=debug

